# Standards: 0.11
---

# 4.1.10 Ensure unsuccessful unauthorized file access attempts are collected (Scored)

- name: 4.1.10 Ensure discretionary access control permission modification events are collected (Scored)
  shell: "grep perm_mod {{ cis_audit_rules_filename }}"
  register: perm_mod
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.10"
    - level-2
    - section-4
    - scored

- name: 4.1.10 Ensure discretionary access control permission modification events are collected (Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.10 Ensure discretionary access control permission modification events are collected'
    - '-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    - '-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    - '-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    - '-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    - '-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    - '-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'

  tags:
    - "4.1.10"
    - level-2
    - section-4
    - scored