# Standards: 0.11
---

# 1.1.15 Ensure nodev option set on /dev/shm partition

# the /dev/shm entry isn't in /etc/fstab by default, add it if it doesn't exist
- name: 1.1.15 - Ensure noexec option set on /dev/shm partition
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
    opts: "defaults,nodev,nosuid,noexec"
  with_items:
    - { mountpoint: "/dev/shm", device: "tmpfs", fstype: "tmpfs" }
  tags:
      - level-1
      - section-1
      - "1.1.17"
      - scored

- name: 1.1.15 - Ensure nodev option set on /dev/shm partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/dev/shm'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.15"
    - scored